# Generated by Django 3.2.8 on 2021-12-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='lable',
            field=models.ManyToManyField(blank=True, related_name='labels', to='users.Label'),
        ),
    ]
