# Generated by Django 3.2.8 on 2021-12-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_task_lable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='lable',
            new_name='lables',
        ),
    ]
