# Generated by Django 3.2.8 on 2021-12-06 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_lable_task_lables'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='lables',
            new_name='labels',
        ),
    ]
